name: TheFirstRun
favicon: null
layout_spectrum: 0.35294
typography_spectrum: 0.41638
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8d8d8'
    - '#2f1c99'
    - '#56d2c8'
    - '#e0332c'
    - '#1a6c8c'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
