name: TheFirstRun
favicon: null
layout_spectrum: 0.35294
typography_spectrum: 0.41638
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8d8d8'
    - '#084500'
    - '#f3eb1e'
    - '#ef3618'
    - '#0c8805'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
